[0m12:46:47.385429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112b97e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11475bc50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11475bed0>]}


============================== 12:46:47.407952 | fc333e84-8af7-416e-99af-062cc84190ef ==============================
[0m12:46:47.407952 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:46:47.408381 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m12:47:40.495494 [debug] [MainThread]: Starter project path: /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/.venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m12:47:40.500074 [info ] [MainThread]:
Your new dbt project "dbt_uss_demo" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:47:40.500464 [info ] [MainThread]: Setting up your profile.
[0m12:47:45.442940 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 58.09557, "process_in_blocks": "0", "process_kernel_time": 0.425581, "process_mem_max_rss": "157188096", "process_out_blocks": "0", "process_user_time": 1.610947}
[0m12:47:45.443362 [debug] [MainThread]: Command `dbt init` succeeded at 12:47:45.443298 after 58.10 seconds
[0m12:47:45.443618 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1149ecb00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11495c710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1147d39b0>]}
[0m12:47:45.443860 [debug] [MainThread]: Flushing usage events
[0m12:47:46.224626 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:03:55.562264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b79be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110ffb9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110ffbc50>]}


============================== 14:03:55.583233 | 7209083a-fc42-4c29-b491-dd9edf885401 ==============================
[0m14:03:55.583233 [info ] [MainThread]: Running with dbt=1.9.8
[0m14:03:55.583759 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:03:55.584164 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m14:03:55.732174 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.2136712, "process_in_blocks": "0", "process_kernel_time": 0.354548, "process_mem_max_rss": "149651456", "process_out_blocks": "0", "process_user_time": 1.60488}
[0m14:03:55.732669 [debug] [MainThread]: Command `dbt run` failed at 14:03:55.732608 after 0.21 seconds
[0m14:03:55.732945 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111119480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11112d910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111154050>]}
[0m14:03:55.733203 [debug] [MainThread]: Flushing usage events
[0m14:03:56.369442 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:01:47.939092 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068db770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119a179d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119a17890>]}


============================== 12:01:47.943604 | e0356cce-712f-480b-b894-0ccc51d485f9 ==============================
[0m12:01:47.943604 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:01:47.943999 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt parse', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:01:47.944375 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:01:47.951092 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.056306083, "process_in_blocks": "0", "process_kernel_time": 0.141005, "process_mem_max_rss": "111378432", "process_out_blocks": "0", "process_user_time": 0.700836}
[0m12:01:47.951422 [debug] [MainThread]: Command `dbt parse` failed at 12:01:47.951364 after 0.06 seconds
[0m12:01:47.951655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119a50e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119a78ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11991d480>]}
[0m12:01:47.951863 [debug] [MainThread]: Flushing usage events
[0m12:01:48.502294 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:01:49.524577 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cdb770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b023b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b023d90>]}


============================== 12:01:49.527764 | af682bd1-cc10-4a66-a9a5-48e4ad2bf27a ==============================
[0m12:01:49.527764 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:01:49.528145 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt docs generate --no-compile', 'send_anonymous_usage_stats': 'True'}
[0m12:01:49.528518 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:01:49.530096 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.041593336, "process_in_blocks": "0", "process_kernel_time": 0.10937, "process_mem_max_rss": "110116864", "process_out_blocks": "0", "process_user_time": 0.679888}
[0m12:01:49.530498 [debug] [MainThread]: Command `dbt docs generate` failed at 12:01:49.530431 after 0.04 seconds
[0m12:01:49.530765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b0510f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b074ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10af1d480>]}
[0m12:01:49.530991 [debug] [MainThread]: Flushing usage events
[0m12:01:50.006776 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:02:12.369413 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1108df770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112f179d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112f17890>]}


============================== 12:02:12.372565 | e0d6f4e7-fc58-48a9-b782-efb739bcc323 ==============================
[0m12:02:12.372565 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:02:12.372929 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt parse', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:02:12.373289 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:02:12.374954 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.04227571, "process_in_blocks": "0", "process_kernel_time": 0.113116, "process_mem_max_rss": "109461504", "process_out_blocks": "0", "process_user_time": 0.666018}
[0m12:02:12.375318 [debug] [MainThread]: Command `dbt parse` failed at 12:02:12.375265 after 0.04 seconds
[0m12:02:12.375553 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112f50e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112f7cef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112e1d480>]}
[0m12:02:12.375765 [debug] [MainThread]: Flushing usage events
[0m12:02:12.948616 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:02:13.926524 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11308b770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11541fb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11541fd90>]}


============================== 12:02:13.929483 | 7ec95e7e-cb50-4ccb-a7c2-9955a841cd20 ==============================
[0m12:02:13.929483 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:02:13.929860 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt docs generate --no-compile', 'send_anonymous_usage_stats': 'True'}
[0m12:02:13.930241 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:02:13.931750 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.040642, "process_in_blocks": "0", "process_kernel_time": 0.101587, "process_mem_max_rss": "109838336", "process_out_blocks": "0", "process_user_time": 0.668135}
[0m12:02:13.932062 [debug] [MainThread]: Command `dbt docs generate` failed at 12:02:13.932016 after 0.04 seconds
[0m12:02:13.932287 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1154510f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x115474ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11531d480>]}
[0m12:02:13.932487 [debug] [MainThread]: Flushing usage events
[0m12:02:14.425541 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:03:42.471865 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a7b770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079179d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107917890>]}


============================== 12:03:42.474705 | 04b6c52c-76dd-4870-8e78-d55f3a2f7862 ==============================
[0m12:03:42.474705 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:03:42.475054 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt parse', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:03:42.475425 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:03:42.477050 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.04031154, "process_in_blocks": "0", "process_kernel_time": 0.110116, "process_mem_max_rss": "109936640", "process_out_blocks": "0", "process_user_time": 0.673073}
[0m12:03:42.477389 [debug] [MainThread]: Command `dbt parse` failed at 12:03:42.477332 after 0.04 seconds
[0m12:03:42.477635 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107950e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107978ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10781d480>]}
[0m12:03:42.477858 [debug] [MainThread]: Flushing usage events
[0m12:03:43.479539 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:03:44.468575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e23770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f1fb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f1fd90>]}


============================== 12:03:44.471503 | 40be07aa-8a95-4da8-ab56-ddd6862f2d3a ==============================
[0m12:03:44.471503 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:03:44.471870 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/linhnguyen/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt docs generate --no-compile', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:03:44.472215 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:03:44.473904 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.041982085, "process_in_blocks": "0", "process_kernel_time": 0.099946, "process_mem_max_rss": "109264896", "process_out_blocks": "0", "process_user_time": 0.672302}
[0m12:03:44.474286 [debug] [MainThread]: Command `dbt docs generate` failed at 12:03:44.474232 after 0.04 seconds
[0m12:03:44.474539 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f510f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f80ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e1d480>]}
[0m12:03:44.474777 [debug] [MainThread]: Flushing usage events
[0m12:03:44.960089 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:34:59.414079 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106737770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a179d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a17890>]}


============================== 12:34:59.417803 | 29ec6961-fdad-4892-b93b-44c7be122bb4 ==============================
[0m12:34:59.417803 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:34:59.418161 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/linhnguyen/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt parse', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:34:59.418500 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:34:59.424367 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.04903804, "process_in_blocks": "0", "process_kernel_time": 0.134835, "process_mem_max_rss": "108429312", "process_out_blocks": "0", "process_user_time": 0.682213}
[0m12:34:59.424679 [debug] [MainThread]: Command `dbt parse` failed at 12:34:59.424630 after 0.05 seconds
[0m12:34:59.424923 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a50e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a78ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11291d480>]}
[0m12:34:59.425133 [debug] [MainThread]: Flushing usage events
[0m12:34:59.981826 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:39:36.744937 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105623770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074179d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107417890>]}


============================== 12:39:36.748673 | be10eaca-3cac-4954-b706-8067e2a4ebaf ==============================
[0m12:39:36.748673 [info ] [MainThread]: Running with dbt=1.9.8
[0m12:39:36.749045 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/linhnguyen/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt parse', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:39:36.749422 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/unified-star-schema-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m12:39:36.751563 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.04476396, "process_in_blocks": "0", "process_kernel_time": 0.140002, "process_mem_max_rss": "108740608", "process_out_blocks": "0", "process_user_time": 0.706813}
[0m12:39:36.751868 [debug] [MainThread]: Command `dbt parse` failed at 12:39:36.751820 after 0.05 seconds
[0m12:39:36.752133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107450e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107480ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10731d480>]}
[0m12:39:36.752339 [debug] [MainThread]: Flushing usage events
[0m12:39:38.095261 [debug] [MainThread]: An error was encountered while trying to flush usage events
